name: cicd-workflow with slack integration
on:
  push:
    branches: [ "main" ]
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - uses: act10ns/slack@v2
      with:
        status: starting
        channel: '#meetups'
        message: Starting Docker Build image...
      if: always()
    - uses: actions/checkout@v3
    - name: Run echo
      run: |
        echo "Hello"
        echo "World"
    - uses: act10ns/slack@v2
      with:
        channel: '#meetups'
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
      if: always()


